# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

steps:
# Build the alpine version.
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'Dockerfile.alpine', '--tag=gcr.io/$PROJECT_ID/go-git:alpine', '.']

# The alpine version is our default.
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/$PROJECT_ID/go-git:alpine', 'gcr.io/$PROJECT_ID/go-git']

images:
- 'gcr.io/$PROJECT_ID/go-git'
- 'gcr.io/$PROJECT_ID/go-git:alpine'
