# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

steps:
# Build the image.
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'Dockerfile', '--tag=gcr.io/local-dialect-223022/protoc-gen-grpc-web', '.']

images:
- 'gcr.io/local-dialect-223022/protoc-gen-grpc-web'
